### ISSUE TITLE
js converter

### ISSUE THREAD

**Issue by Arinerron** [Quintec/LaserLang#1]
can u make a js -> laserlang converter pls

**Comment by Aplet123** [comment]
+1. This is a great idea. Please do.

**Comment by Arinerron** [comment]
it would help beginners get into the lang

**Comment by DarinMao** [comment]
+1. A JavaScript transpiler is a worthy addition to any serious language.

**Comment by karmanyaahm** [comment]
Yes, absolutely

**Comment by diogoscf** [comment]
If this could be done before Monday the 13th of June at 17:00 UTC, I'd be very grateful

**Comment by Arinerron** [comment]
Thank you, our team has finished the project and we are running it through QA. We anticipate project delivery before 13th of June at 17:00 UTC

**Comment by karmanyaahm** [comment]
Past due

**Comment by Quintec** [comment]
Looks like QA has deemed the code unworthy of release, unfortunately
