### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by deut-erium** [Quintec/LaserLang#6]
Bounce back to bounce the ray back in its original direction ( not sure if it can be useful, but a suggestion nevertheless)
| Mirror | Direction changes (from -> to) |
| ------ | ------------------------------ |
| `\|` | Horizontal bounce back, up -> up, left -> right, down -> down, right -> right |
| `_` | Vertical bounce back, up -> down, left -> left, down -> up, right -> right |

| Op | Description | Stack (before) | Stack (after) | Notes |
| -- | ----------- | -------------- | ------------- | ----- |
| `z` | Debug stack | `[[a, b, c],[d,e,f]]` | `[[a, b, c],[d,e,f]]` | Prints out the whole stack of stacks for debugging without affecting the stacks  |

**Comment by Quintec** [comment]
I had considered this, but `|` is currently bitwise or and quite frankly I can't think of a use case. Debug stack might be useful, but I'll note Laser has verbose mode (pass `-v` as an argument) for debugging.

**Comment by deut-erium** [comment]
Bounce is not much of use, could be there just for fun.  
Debug stack could be useful to print just the required values, say `z` prints the current stack and `Z` prints all stacks as verbose prints too much output.  
Also, please mention the command line flags (just like verbose) on README

**Comment by Quintec** [comment]
Right, added flags to README. I don't want to add debug commands to a programming language, so I'll just note that print current stack can be achieved with `ROP`.
